# Generated by Django 6.0 on 2025-12-17 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(choices=[('IT', 'Information Technology'), ('FINANCE', 'Finance & Banking'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('ECOMMERCE', 'E-commerce'), ('MANUFACTURING', 'Manufacturing'), ('CONSULTING', 'Consulting'), ('STARTUP', 'Startup'), ('OTHER', 'Other')], max_length=50)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('company_size', models.CharField(blank=True, max_length=50, null=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recruiters',
                'ordering': ['-created_at'],
            },
        ),
    ]
