# Generated by Django 6.0 on 2025-12-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('APPLICATION', 'Application Update'), ('INTERVIEW', 'Interview Schedule'), ('JOB', 'New Job Posted'), ('APPROVAL', 'Account Approved'), ('SYSTEM', 'System Notification')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('total_students', models.IntegerField(default=0)),
                ('students_placed', models.IntegerField(default=0)),
                ('placement_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('branch_wise_stats', models.JSONField(blank=True, default=dict)),
                ('average_package', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('highest_package', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'placement_statistics',
                'ordering': ['-academic_year'],
            },
        ),
    ]
